// Module2_FrontendDev/handson_07/src/app/course-card.component.ts
import { Component, Input } from "@angular/core";

@Component({
selector: "app-course-card",
standalone: true,
template: `
<article class="course-card">
<h3>{{ title }}</h3>
<p>{{ tag }}</p>
<span>{{ units }} credits</span>
</article>
`
})
export class CourseCardComponent {
@Input() title = "";
@Input() tag = "";
@Input() units = 0;
}

// Module2_FrontendDev/handson_08/src/components/CourseCard.vue
<template>
<article class="course-card">
<h3>{{ title }}</h3>
<p>{{ tag }}</p>
<span>{{ units }} credits</span>
</article>
</template>

<script setup>
defineProps({ title: String, tag: String, units: Number });
</script>

<style scoped>
.course-card { padding: 16px; border: 1px solid #ddd; border-radius: 8px; }
</style>
